package dad.recetapp.view.controller;

import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Button;
import javafx.scene.control.TextField;
import javafx.event.ActionEvent;
import javafx.scene.control.TableView;
import javafx.scene.control.TableColumn;
import javafx.scene.image.ImageView;

public class CPNuevaRecetaController {
	@FXML
	private TextField seccionText;
	@FXML
	private Button menosButton;
	@FXML
	private TableView ingredienteTable;
	@FXML
	private TableColumn cantidadColumn;
	@FXML
	private TableColumn medidaColumn;
	@FXML
	private TableColumn tipoColumn;
	@FXML
	private Button nuevoIngredienteButton;
	@FXML
	private Button editarIngredienteButton;
	@FXML
	private Button eliminarIngredienteButton;
	@FXML
	private Button nuevaInstruccionButton;
	@FXML
	private Button editarInstruccionButton;
	@FXML
	private Button eliminarInstruccionButton;
	@FXML
	private TableView instruccionTable;
	@FXML
	private TableColumn ordenColumn;
	@FXML
	private TableColumn descripcionColumn;
	
	@FXML
	public void initialize(){
		nuevoIngredienteButton.setGraphic(new ImageView("dad/recetapp/ui/images/add-icon-20x20.png"));
		editarIngredienteButton.setGraphic(new ImageView("dad/recetapp/ui/images/edit-icon-20x20.png"));
		eliminarIngredienteButton.setGraphic(new ImageView("dad/recetapp/ui/images/delete-icon-20x20.png"));
		
		nuevaInstruccionButton.setGraphic(new ImageView("dad/recetapp/ui/images/add-icon-20x20.png"));
		editarInstruccionButton.setGraphic(new ImageView("dad/recetapp/ui/images/edit-icon-20x20.png"));
		eliminarInstruccionButton.setGraphic(new ImageView("dad/recetapp/ui/images/delete-icon-20x20.png"));
	}

	// Event Listener on Button[#menosButton].onAction
	@FXML
	public void menos(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#nuevoIngredienteButton].onAction
	@FXML
	public void nuevoIngrediente(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#editarIngredienteButton].onAction
	@FXML
	public void editarIngrediente(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#eliminarIngredienteButton].onAction
	@FXML
	public void eliminarIngrediente(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#nuevaInstruccionButton].onAction
	@FXML
	public void nuevaInstruccion(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#editarInstruccionButton].onAction
	@FXML
	public void editarInstruccion(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#eliminarInstruccionButton].onAction
	@FXML
	public void eliminarInstruccion(ActionEvent event) {
		// TODO Autogenerated
	}
}
