package dad.recetapp.view.controller;

import java.awt.event.ActionListener;
import java.io.IOException;

import javax.swing.plaf.basic.BasicTabbedPaneUI.TabbedPaneLayout;

import dad.recetapp.services.ServiceException;
import dad.recetapp.services.ServiceLocator;
import dad.recetapp.services.items.CategoriaItem;
import dad.recetapp.view.MainApp;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.control.TextField;
import javafx.beans.value.ChangeListener;
import javafx.event.ActionEvent;
import javafx.event.Event;
import javafx.event.EventHandler;
import javafx.scene.control.ComboBox;
import javafx.scene.control.Tab;
import javafx.scene.control.TabPane;
import javafx.scene.layout.BorderPane;

public class NuevaRecetaController {
	@FXML
	private TextField nombreText;
	@FXML
	private ComboBox<String> categoriaCombo;
	@FXML
	private TextField paraText;
	@FXML
	private ComboBox<String> paraCombo;
	@FXML
	private ComboBox<String> minutosTotalCombo;
	@FXML
	private ComboBox<String> segundosTotalCombo;
	@FXML
	private ComboBox<String> minutosThermoCombo;
	@FXML
	private ComboBox<String> segundosThermoCombo;
	@FXML
	private Tab seccionTab;
	@FXML
	private Tab nuevaTab;
	@FXML
	private TabPane tabPane;


	@FXML
	public void initialize() {
		try {
			categoriaCombo.getItems().add("<Seleccione una Categoria>");
			for (CategoriaItem categoriaItem : ServiceLocator.getCategoriasService().listarCategorias()) {
				categoriaCombo.getItems().add(categoriaItem.getDescripcion());
			}
		} catch (ServiceException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

		categoriaCombo.setValue("<Seleccione una Categoria>");
		paraText.setText("0");
		paraCombo.getItems().add("Personas");
		paraCombo.setValue("Personas");
		for (int j = 0; j < 61; j++) {
			segundosTotalCombo.getItems().add(String.valueOf(j));
		}
		segundosTotalCombo.setValue("0");
		for (int j = 0; j < 301; j++) {
			minutosTotalCombo.getItems().add(String.valueOf(j));
		}
		minutosTotalCombo.setValue("0");

		for (int j = 0; j < 61; j++) {
			segundosThermoCombo.getItems().add(String.valueOf(j));
		}
		segundosThermoCombo.setValue("0");
		for (int j = 0; j < 301; j++) {
			minutosThermoCombo.getItems().add(String.valueOf(j));
		}
		minutosThermoCombo.setValue("0");

		nuevaTab.onSelectionChangedProperty().set(new EventHandler<Event>() {
			
			@Override
			public void handle(Event event) {
				Tab nuevo =new Tab("");
				tabPane.getTabs().add(tabPane.getTabs().size()-1,nuevo);
				FXMLLoader loader = new FXMLLoader(MainApp.class.getResource("CPNuevaRecetaView.fxml"));
				BorderPane ventanaDos;
				try {
					ventanaDos = (BorderPane) loader.load();
					nuevo.setContent(ventanaDos);
				} catch (IOException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
				
				tabPane.getSelectionModel().select(nuevo);
				
			}
		});


	}

	// Event Listener on Button.onAction
	@FXML
	public void crear(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button.onAction
	@FXML
	public void cancelar(ActionEvent event) {
		// TODO Autogenerated
	}


}
